# Generated by Django 4.2.24 on 2025-09-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raum", models.CharField(max_length=45)),
                ("ip", models.CharField(max_length=45)),
                ("code", models.TextField()),
            ],
            options={"db_table": "sensor", "managed": True,},
        ),
        migrations.CreateModel(
            name="Werte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("luftdruck", models.FloatField()),
                ("luftfeuchte", models.FloatField()),
                ("temperatur", models.FloatField()),
                ("datum", models.DateTimeField()),
                (
                    "sen",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="web.sensor",
                    ),
                ),
            ],
            options={"db_table": "werte", "managed": True,},
        ),
    ]
