"""
superuser: bx, Q34Rna$f4re
Django settings for smarthomeweb_proj project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ys(etcns19lin)zyl==u^b2o5gsqr-ze)7!h1)jxb*m(0w2z=b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # "daphne" muss GANZ OBEN stehen: dadurch startet "runserver" automatisch den
    # ASGI-/Daphne-Server, der WebSockets kann (statt des reinen HTTP-Dev-Servers).
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "web",  # Wichtig, sonst werden die HTML-Seiten nicht gefunden.
    "rest_framework",
    "bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smarthomeweb_proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "smarthomeweb_proj.wsgi.application"

# --- WebSockets / Django Channels ---------------------------------------------
# Einstiegspunkt für ASGI. Darüber laufen die WebSocket-Verbindungen (siehe asgi.py).
ASGI_APPLICATION = "smarthomeweb_proj.asgi.application"

# Der "Channel Layer" ist die Vermittlungsstelle, über die der Server EINE Nachricht
# an mehrere verbundene Browser gleichzeitig schicken kann (Broadcast an eine Gruppe).
# InMemory = einfachste Variante, kein Redis nötig – ideal zum Entwickeln/Lernen.
# (Für echten Mehrprozess-/Produktivbetrieb würde man später auf Redis umstellen.)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# --- MQTT (Sensordaten vom ESP32) ---------------------------------------------
# Der ESP32 (Adafruit Feather, siehe D:/code.py) sendet seine BME280-Messwerte
# an diesen Broker. Django hört mit und zeigt/speichert die Werte.
# WICHTIG: Die Broker-IP ändert sich je nach Netzwerk/Hotspot – hier anpassen!
MQTT_ENABLED = True                  # auf False setzen, wenn gerade kein Broker läuft
MQTT_BROKER = "172.20.10.8"          # IP-Adresse des MQTT-Brokers
MQTT_PORT = 1883
MQTT_USERNAME = ""                   # leer = keine Anmeldung nötig
MQTT_PASSWORD = ""
MQTT_TOPIC = "smarthome/sensor/#"    # "#" = alle Sensoren + alle Messgrößen abonnieren


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "smarthome",  # Name der DB mit den Werten.
        "HOST": "localhost",
        "USER": "root",
        "PASSWORD": "",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


USE_L10N = True
